import { StandardJWE } from "./jwe.model";
import { IDTypePair } from "./jsonApi.model";
/** If the data is less than the chunk size, it is embedded directly into the content.
 *  Otherwise, the data is sharded into chunks by the client, and each chunk is encrypted and sent to the server.
 *  In this case, content contains a manifest-like listing of URIs to individual chunks (integrity-protected by [HASHLINK].
 *  Required fields are "created" and "status".
 *  - created (REQUIRED): UNIX epoch time (miliseconds) instead of ISO datetime, required when creating a document.
 *  - status (REQUIRED): valid status for the composition are "preliminary", "amended", "final" or "error" (FHIR specification).
 *  - contentType (Conditional): MIME type, required when data is sharded into chunks (e.g.: "didcomm-plain+json").
 *  - tags (Conditional): non-personal data, it is required when the content data is created. The tags can be removed from the metadata and stored in the encrypted index.
 *  - sectionCode (Conditional): required code for a health section or document category in a personal wallet.
 *  - sectionSystem (Conditional): default is "http://loinc.org" (health section or health document category).
 *  - updated (Conditional): UNIX epoch time (miliseconds) instead of ISO datetime, required when updating a document; it can be used as the version of the composition.
 *  - deactivated (Conditional): required when the storage object is disabled (before deleting).
 *  Note: the deactivation date is the "updated" timestamp.
 */
export interface MetaDataComposition {
    contentType?: string;
    sectionCode?: string;
    sectionSystem?: string;
    status: string;
    created: number;
    deactivated?: boolean;
    updated?: number;
    tags?: string[];
}
/** Unencrypted composition data to be encrypted before being stored and sent to an external Encrypted Data Vault (EDV).
 *  When creating a draft, the required properties are: `id`, `indexed`, `meta.created`, `meta.status`.
 *  - the `indexed` element contains safe or unsafe index of attributes (`name` and `value`).
 *  - the `id` property is the external EDV record ID (16 bits), it can be generated deterministically.
 *  - the `_id` property is the internal identifier self-generated by the DB (PouchDB, CouchDB, MongoDB).
 *  - the `meta` property contains:
 *      - created (REQUIRED): UNIX epoch time (miliseconds) instead of ISO datetime, required when creating a document.
 *      - status (REQUIRED): valid status for the composition are "preliminary", "amended", "final" or "error" (FHIR specification).
 *      - contentType (Conditional): MIME type, required when data is sharded into chunks (e.g.: "didcomm-plain+json").
 *      - tags (Conditional): non-personal data, it is required when the content data is created.
 *      - sectionCode (Conditional): required code for a health section or document category in a personal wallet.
 *      - sectionSystem (Conditional): default is "http://loinc.org" (health section or health document category).
 *      - updated (Conditional): UNIX epoch time (miliseconds) instead of ISO datetime, required when updating a document; it can be used as the version of the composition.
 *      - deactivated (Conditional): required when the storage object is disabled (before deleting).
 *  Note: the deactivation date is the "updated" timestamp.
 */
export interface DataStorageBase {
    "_deleted"?: boolean;
    "_id"?: string;
    "_rev"?: string;
    id?: string;
    indexed?: any;
    meta?: MetaDataComposition;
}
/** Unencrypted composition data to be encrypted before being stored and sent to an external Encrypted Data Vault (EDV).
 *  When creating a draft, the required properties are: `_id`, `index` (`title` attribute), `meta.created`, `meta.status`.
 * - the `content` property contains the unencrypted DIDComm payload (with additional "body", "body.data[]" and "body.data[].attributes" properties).
 * - the `indexed` property contains unsafe index of attributes (`name` and `value`), not protected by HMAC.
 * - the `meta` property contains:
 *      - created (REQUIRED): UNIX epoch time (miliseconds) instead of ISO datetime, required when creating a document.
 *      - status (REQUIRED): valid status for the composition are "preliminary", "amended", "final" or "error" (FHIR specification).
 *      - contentType (Conditional): MIME type, required when data is sharded into chunks (e.g.: "didcomm-plain+json").
 *      - tags (Conditional): non-personal data, it is required when the content data is created.
 *      - sectionCode (Conditional): required code for a health section or document category in a personal wallet.
 *      - sectionSystem (Conditional): default is "http://loinc.org" (health section or health document category).
 *      - updated (Conditional): UNIX epoch time (miliseconds) instead of ISO datetime, required when updating a document; it can be used as the version of the composition.
 *      - deactivated (Conditional): required when the storage object is disabled (before deleting).
 *  Note: the deactivation date is the "updated" timestamp.
 */
/** Decrypted indexed attributes, they SHALL be encrypted before being stored.
 *  The `title` attribute MUST exist (human readable title for the composition)
 */
export interface IndexAttributeUnprotected {
    attributes: IndexAttributeUnsafe[];
}
/** Unsafe indexed attributes can be protected by HMAC and used to perform efficient searching
 *  to protect the privacy of entities that are storing information in the data vault.
 *  When creating a document composition, index properties MAY be used to perform efficient searches.
 */
export interface IndexAttributeUnsafe {
    name: string;
    value: string;
    unique?: boolean;
}
/** Safe indexed attributes can be created and used to perform efficient searching
 *  while protecting the privacy of entities that are storing information in the data vault.
 *  When creating an encrypted document composition, blinded index properties MAY be used to perform efficient searches.
 */
export interface IndexedAttributeProtected {
    name: string;
    value: string;
    unique?: boolean;
}
/** IndexedDataHMAC represents a collection of indexed attributes, all of which share a common MAC algorithm and key.
 *  This format is based on https://identity.foundation/confidential-storage/#creating-encrypted-indexes.
 *  Encrypted indexes can be created and used to perform efficient searching
 *  while protecting the privacy of entities that are storing information in the data vault.
 *  When creating an encrypted resource, blinded index properties MAY be used to perform efficient searches.
 *  - "attributes" contains the indexed attributes (HMAC protected)
 *  - "hmac" contains both HMAC key "id" (e.g. `did:ex:12345#key1`) and "type" (e.g. `Sha256HmacKey2019`).
 *  - "sequence" ...
 */
export interface IndexProtected {
    attributes: IndexedAttributeProtected[];
    hmac: IDTypePair;
    sequence: number;
}
/** Encrypted composition data to be stored on an Encrypted Data Vault (EDV).
 *  When creating a draft, the required properties are: `_id`, `indexed` (`title` attribute), `meta.created`, `meta.status`.
 * - the `jwe` element contains the encrypted data ('cipertext property).
 * - the `indexed` element contains safe indexed attributes (HMAC).
 * - the `meta` element contains:
 *      - status (REQUIRED): valid status for the composition are "preliminary", "amended", "final" or "error" (FHIR specification).
 *      - created (REQUIRED): UNIX epoch time (miliseconds) instead of ISO datetime, required when creating a document.
 *      - deactivated (Conditional): required when the storage object is disabled (before deleting).
 *      - updated (Conditional): UNIX epoch time (miliseconds) instead of ISO datetime, required when updating a document; it can be used as the version of the composition.
 *      - contentType (Conditional): MIME type, required when data is sharded into chunks (e.g.: "didcomm-plain+json").
 *      - sectionCode (Conditional): required code for a health section or document category in a personal wallet.
 *      - sectionSystem (Conditional): default is "http://loinc.org" (health section or health document category).
 *      - tags (Conditional): non-personal data, it is required when the content data is created.
 *  Note: the deactivation date is the "updated" timestamp.
 */
export interface SecureStorageData extends // note: old StorageBase
DataStorageBase {
    indexed?: IndexProtected;
    jwe?: StandardJWE;
}
